// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jjvlnwkfnwmcmhmzvkdd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impqdmxud2tmbndtY21obXp2a2RkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5ODM5MzAsImV4cCI6MjA2NTU1OTkzMH0.xYMgVG19rfnaBflXp2MYvbVM_jSJ7ulySi4fj936630";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);